project:
  type: website
  output-dir: _site

render:
  on-save: true

website:
  title: "Dissertation Defense"
  site-url: "https://rvandewater.github.io/dissertation-defense/"
  
format:
  html:
    theme: default
